### ISSUE TITLE
Make a Spring Boot example app to demontrate the use of Casdoor-Java-SDK

### ISSUE THREAD

**Issue by hsluoyz** [casdoor/casdoor-spring-boot-example#1]
https://github.com/casdoor/casdoor-java-sdk is basically usable after PR: https://github.com/casdoor/casdoor-java-sdk/pull/6 . We can make an example here to show how to use it.

At this early stage, we can directly use casdoor-java-sdk, but in future, we may change to use a stronger wrapper: https://github.com/casdoor/casdoor-spring-boot-starter

So here are two paths:

1. For now: casdoor-spring-boot-example --> casdoor-java-sdk
2. In future: casdoor-spring-boot-example --> casdoor-spring-boot-starter --> casdoor-java-sdk

**Comment by hsluoyz** [comment]
@seriouszyx this can be next step.

**Comment by seriouszyx** [comment]
OK! I'll do it
